export const ROUTES = {
  home: '/',
  products: '/products',
  productDetails: '/products/:slug',
  categories: '/categories',
  about: '/about',
  contact: '/contact',
  cart: '/cart',
  login: '/login',
  register: '/register',
  customerDashboard: '/customer/dashboard',
  customerProfile: '/account/profile',
  customerOrders: '/account/orders',
  customerReviews: '/account/reviews',
  customerAddresses: '/account/addresses',
  ownerDashboard: '/owner/dashboard',
  ownerOrders: '/owner/orders',
  ownerProducts: '/owner/products',
  ownerAddProduct: '/owner/products/new',
  ownerEditProduct: '/owner/products/:productId/edit',
  ownerCategories: '/owner/categories',
  ownerCustomers: '/owner/customers',
  ownerReviews: '/owner/reviews',
  ownerProfile: '/owner/profile',
  ownerSettings: '/owner/settings',
  ownerPassword: '/owner/password',
} as const;
